import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className="flex min-h-full flex-col">
        {children}
        <Toaster />

        <Footer />
      </body>
    </html>
  )
}
